### PR TITLE
V0.5.0 forward merge

### PR DESCRIPTION
**Pull request by ayushdg**
## Description
Merge in changes from the 0.5.0 release into main.
Specifically excludes the changes around our requirements.txt being pinned to specific versions in the previous release.

Also bumps our current version to 0.6.0.dev0 for folks installing from source.

## Usage
N/A

## Checklist

- [X] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [X] New or Existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by ayushdg** [comment]
Not sure if the DCO errors are applicable here or not. Seems to be some weird mismatch in expected email addresses from an old commit. I'm tempted to set DCO to pass unless someone has suggestions.

**Comment by VibhuJawa** [comment]
> Not sure if the DCO errors are applicable here or not. Seems to be some weird mismatch in expected email addresses from an old commit. I'm tempted to set DCO to pass unless someone has suggestions.

I think that is fine, but if you want to, you can always rebase and fix commit message for that commit with that email

**Review by ryantwolf — APPROVED** [review]
Yeah I'm fine setting the DCO to pass. Do you know which commit in particular is causing problems?

**Review by VibhuJawa — APPROVED** [review]

**Comment by ayushdg** [comment]
> Yeah I'm fine setting the DCO to pass. Do you know which commit in particular is causing problems?

Commit sha: [1dddfed](https://github.com/NVIDIA/NeMo-Curator/pull/340/commits/1dddfedeeee3818102ee67676a8cf832c743ee5f), Author: Praateek Mahajan, Committer: GitHub; Can not find "Praateek Mahajan [praateekmahajan@users.noreply.github.com](mailto:praateekmahajan@users.noreply.github.com)", in ["Praateek Mahajan [praateekm@gmail.com](mailto:praateekm@gmail.com)", "Praateek Mahajan [praateekm@gmail.com](mailto:praateekm@gmail.com)", "Praateek Mahajan [praateekm@gmail.com](mailto:praateekm@gmail.com)", "Praateek Mahajan [praateekm@gmail.com](mailto:praateekm@gmail.com)", "Praateek Mahajan [praateekm@gmail.com](mailto:praateekm@gmail.com)", "Praateek Mahajan [praateekm@gmail.com](mailto:praateekm@gmail.com)"].
Commit sha: [017ff97](https://github.com/NVIDIA/NeMo-Curator/pull/340/commits/017ff974408089b9dc0654e9700e0807879688be), Author: Praateek Mahajan, Committer: GitHub; Expected "Praateek Mahajan [praateekmahajan@users.noreply.github.com](mailto:praateekmahajan@users.noreply.github.com)", but got "Praateek Mahajan [praateekm@gmail.com](mailto:praateekm@gmail.com)".

It's a commit that's already in the other branch untouched by the merge.

**Comment by ryantwolf** [comment]
hold off one second until Tanay gets his fix in.

**Comment by ryantwolf** [comment]
@ayushdg I think we're good now, any reservations on merging?

**Comment by ayushdg** [comment]
Nope. I also think I understand the source of the DCO confusion. When merging in a PR, GitHub UI asks for an email address to associate with the merge commit into the branch. If that email address doesn't typically match the email addresses used by a developer for signing off commits, DCO gets a bit thrown off, because we now have a squash & merge commit from a different email address than the one used to sign off commits in the git history.

**Pull request merged**
