### PR TITLE
Fix bug #105

### PR DESCRIPTION
**Pull request by nicoleeeluo**
## Description

This PR is to fix the bug in #105 by updating the code to latest version

## Usage

```python
# Add snippet demonstrating usage
```
## Checklist

- [ ] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [ ] New or Existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by miguelusque** [comment]
Hi @nicoleeeluo ,

Thank you for your fix.

I think that,instead of passing `None` to `input_meta`, I would change `io_utils.py` as follows:

> def get_text_ddf_from_json_path_with_blocksize(
>     input_data_paths, num_files, blocksize, id_column, text_column, input_meta=None
> ):

That would fix not only this notebook, but any other potential case.

Looking forward for your thoughts about it. Thanks!

**Comment by ryantwolf** [comment]
I agree with @miguelusque 's suggestion, it should allow you to keep your tutorial unchanged!

**Comment by nicoleeeluo** [comment]
@miguelusque @ryantwolf Changing `io_utils.py` sounds good to me! If the change on `io_utils.py` has been made, I will discard this PR.

**Comment by ryantwolf** [comment]
Fix was made in #69 . Closing

**Pull request closed without merging**
